"""empty message

Revision ID: 5c6148349d1a
Revises: 686f29a99478
Create Date: 2017-01-26 14:20:14.024092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6148349d1a'
down_revision = '686f29a99478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('min_limit', sa.Float(), nullable=True),
    sa.Column('max_limit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['project_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisory_limits')
    # ### end Alembic commands ###
