"""empty message

Revision ID: 686f29a99478
Revises: e79193ad4d04
Create Date: 2017-01-23 12:18:55.711271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686f29a99478'
down_revision = 'e79193ad4d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_info_page', sa.Column('swim_advisory_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_info_page', 'swim_advisory_info')
    # ### end Alembic commands ###
