"""empty message

Revision ID: 8ca3d6218f9c
Revises: 5c6148349d1a
Create Date: 2017-01-26 14:51:01.758325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca3d6218f9c'
down_revision = '5c6148349d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_limits', sa.Column('icon', sa.String(length=32), nullable=True))
    op.add_column('advisory_limits', sa.Column('limit_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advisory_limits', 'limit_type')
    op.drop_column('advisory_limits', 'icon')
    # ### end Alembic commands ###
